import json
import re

with open("client/src/data/kml-pandals.json", "r", encoding="utf-8") as f:
    pandals = json.load(f)

# Specific curated descriptions for notable pujas
CUSTOM_DESCRIPTIONS = {
    "kml-001": "Iconic North Kolkata heritage puja celebrated for magnificent traditional artistry, vibrant cultural themes, and riverside charm.",
    "kml-002": "Famed for breathtaking architectural monument replicas illuminated over the historic lake with mesmerizing night reflections.",
    "kml-003": "Prominent VIP Road residential complex puja known for grand thematic decor, festive lighting, and vibrant community celebrations.",
    "kml-004": "Award-winning art destination along Dum Dum Park celebrated for intricate hand-sculpted installations, conceptual themes, and ambient lighting.",
    "kml-005": "Premier Dum Dum Park attraction renowned for innovative eco-friendly craftsmanship, contemporary artistic sculptures, and cultural resonance.",
    "kml-006": "Popular North-East Kolkata pandal known for creative thematic installations, festive illuminations, and community cultural heritage.",
    "kml-007": "Celebrated Dum Dum Park youth club famous for artistic pandal designs, lively festive atmosphere, and innovative idol styling.",
    "kml-008": "Historic centenary barowari celebration (est. 1919) famous for its timeless Ekchala Daker Saaj idol, classic rituals, and grand carnival.",
    "kml-009": "Landmark VIP Road puja known for sprawling thematic structures, creative illuminations, and bustling festive footfall.",
    "kml-010": "Pioneer of North Kolkata theme pujas along Ultadanga, celebrated for intricate handicrafts, natural material decor, and artistic idols.",
    "kml-011": "Vibrant Ultadanga neighborhood puja famous for colorful thematic decor, folk artisan motifs, and warm community festivities.",
    "kml-012": "Heritage North Kolkata puja known for rich traditional rituals, artistic lighting displays, and festive hospitality.",
    "kml-013": "Grand celebration adjoining the potters' colony, renowned for massive architectural facades and contemporary artistic installations.",
    "kml-014": "Premier Lake Town celebration celebrated for lavish architectural structures, vibrant festive illuminations, and traditional fervor.",
    "kml-015": "Popular Lake Town sporting club known for energetic cultural programs, artistic pandal decor, and festive gatherings.",
    "kml-016": "Major Central Kolkata crowd-puller celebrated for towering monument replicas, illuminated fountains, and colorful lighting.",
    "kml-017": "Famed Kankurgachi neighborhood celebration known for artistic craftsmanship, social themes, and harmonious idol aesthetics.",
    "kml-018": "Renowned Salt Lake Sector-II celebration known for grand royal temple architecture, cultural performances, and traditional idol.",
    "kml-019": "Famous Salt Lake ground puja celebrated for magnificent palace replicas, festive fairs, and massive community gatherings.",
    "kml-020": "Salt Lake's most celebrated mega-puja, attracting lakhs of visitors for its colossal fantasy architecture, laser shows, and grand themes.",
    "kml-021": "Popular Salt Lake block puja known for creative artistic motifs, eco-friendly materials, and traditional family warmth.",
    "kml-022": "Vibrant Salt Lake residential celebration featuring artistic pandal architecture, festive lighting, and cultural programs.",
    "kml-023": "Charming Salt Lake block puja celebrated for traditional idol modeling, cultural unity, and festive community feasts.",
    "kml-024": "Historic Salt Lake estate celebration known for serene residential ambiance, traditional rituals, and warm community bhog.",
    "kml-025": "Superstar Central Kolkata spectacle renowned for ultra-luxurious gold/diamond themed sets, laser shows, and record-breaking crowds.",
    "kml-026": "Historic Central Kolkata celebration established in 1947 near Sealdah station, celebrated for traditional rituals and railway sporting heritage.",
    "kml-027": "Historic North Kolkata neighborhood puja celebrated for authentic traditional idol artistry, heritage lane decor, and classic rituals.",
    "kml-028": "Mega VIP Road attraction renowned for lavish world-famous monument replicas (Burj Khalifa, Vatican, Ram Mandir) and real gold-adorned idols.",
    "kml-029": "Pioneering North Kolkata barowari celebration (est. 1921) celebrated for its century-old heritage, traditional idol, and festive fairs.",
    "kml-030": "Renowned Manicktala celebration famous for pioneering glass/brass artisanal themes, eco-friendly decor, and spirited dhak contests.",
    "kml-031": "Historic North Kolkata lane puja celebrated for intimate community warmth, traditional clay artistry, and cultural heritage.",
    "kml-032": "Vibrant Tala neighborhood celebration noted for creative contemporary pandal themes, artistic lighting, and community fervor.",
    "kml-033": "Charming North Kolkata riverside celebration known for traditional idol craftsmanship and peaceful festive ambiance.",
    "kml-034": "Famous Hatibagan theme powerhouse renowned for creative rural and folk art motifs, intricate woodwork, and cultural depth.",
    "kml-035": "Acclaimed North Kolkata art hub celebrated for exquisite terracotta and clay sculpture installations blending heritage with modern aesthetics.",
    "kml-036": "Century-old heritage celebration along the historic Hatibagan theater corridor, noted for traditional idol decor and cultural nostalgia.",
    "kml-037": "Historic Howrah barowari celebration known for century-old traditional rituals, classic idol craftsmanship, and local community fervor.",
    "kml-038": "Energetic North Kolkata youth club puja celebrated for vibrant thematic pandal designs, lighting, and community warmth.",
    "kml-039": "Award-winning North Kolkata thematic powerhouse celebrated for deeply emotional social, literary, and environmental art installations.",
    "kml-040": "Celebrated Salt Lake area puja known for creative pandal structures, cultural events, and festive community harmony.",
    "kml-041": "Historic royal household puja founded in 1757 by Raja Nabakrishna Deb; famed for its grand Natmandir courtyard and Ekchala Daker Saaj idol.",
    "kml-042": "Renowned Sealdah-Amherst Street celebration known for thought-provoking contemporary social themes and artistic installations.",
    "kml-043": "Salt Lake Sector-II block puja noted for traditional idol craftsmanship, festive illuminations, and community cultural performances.",
    "kml-044": "Vibrant Lake Town neighborhood celebration known for innovative pandal decor, colorful lighting, and festive warmth.",
    "kml-045": "Historic North Kolkata celebration named after Raja Ram Mohan Roy, known for cultural heritage, social themes, and classic idol.",
    "kml-046": "Intimate North Kolkata heritage lane puja celebrated for traditional family warmth, sabeki idol, and neighborhood festive bonding.",
    "kml-047": "Historic Dakshineswar riverside celebration noted for age-old traditional rituals, devotional atmosphere, and heritage idol craftsmanship.",
    "kml-048": "Popular North suburban puja near Baranagar known for grand pandal architecture, festive fairs, and community celebrations.",
    "kml-049": "Prominent Dum Dum Motijheel celebration known for creative thematic installations, festive illuminations, and large footfall.",
    "kml-050": "Lively Beliaghata neighborhood celebration known for artistic pandal designs, festive gatherings, and community harmony.",
    "kml-051": "Popular Beliaghata club celebrated for innovative contemporary themes, vibrant lighting, and festive cultural events.",
    "kml-052": "Historic nationalist puja founded in 1926 with blessings of Netaji Subhas Chandra Bose, famous for its fierce traditional warrior-form idol.",
    "kml-053": "Energetic North Kolkata club puja known for creative thematic decor, youth participation, and festive community spirit.",
    "kml-054": "Located in the heart of Kolkata's legendary idol-makers' hub Kumartuli, showcasing raw clay craftsmanship and sacred sculpting traditions.",
    "kml-055": "Popular Kankurgachi neighborhood celebration noted for colorful artistic pandals, festive fairs, and community bonding.",
    "kml-056": "Award-winning North Kolkata theme puja celebrated for extraordinary botanical, eco-friendly, and seed-crafted temple installations.",
    "kml-057": "Vibrant Manicktala-Lalabagan neighborhood celebration known for artistic pandal decor, traditional rituals, and community warmth.",
    "kml-058": "Prominent Salt Lake Sector-I puja celebrated for monumental architecture, cultural programs, and grand community dining.",
    "kml-059": "Central Kolkata festive landmark celebrating the cosmopolitan spirit, architectural lights, and joy of the city of joy.",
    "kml-060": "Renowned VIP Road CIT Scheme celebration known for creative artistic themes, festive illuminations, and community fervor.",
    "kml-061": "North Kolkata neighborhood landmark celebrated for its traditional idol craftsmanship and deep-rooted autumnal festivities.",
    "kml-062": "Acclaimed Beliaghata theme destination celebrated for rural Bengal folk art, handmade craft installations, and nostalgic decor.",
    "kml-063": "Century-old Belgachia barowari puja celebrated for traditional rituals, heritage idol styling, and neighborhood cultural unity.",
    "kml-064": "Historic barowari celebration in Kumartuli, revered for master artisan clay sculpting and sacred traditional heritage.",
    "kml-065": "North Kolkata neighborhood club celebrated for artistic thematic pandals, cultural functions, and festive enthusiasm.",
    "kml-066": "Popular Salt Lake Sector-I ground puja noted for grand pavilion designs, festive food stalls, and community cultural events.",
    "kml-067": "Vibrant Salt Lake Sector-I block puja known for creative artistic craftsmanship, lighting displays, and family celebrations.",
    "kml-068": "Salt Lake Sector-II twin-block celebration known for cohesive community spirit, traditional idol, and festive fairs.",
    "kml-069": "Salt Lake residential block puja noted for peaceful festive ambiance, traditional rituals, and cultural gatherings.",
    "kml-070": "Central Salt Lake housing complex puja near Karunamayee, known for colorful illuminations and community festivities.",
    "kml-071": "Historic Howrah temple-side celebration celebrated for traditional rituals, devotional atmosphere, and community feasts.",
    "kml-072": "Prominent Howrah neighborhood club celebrated for creative thematic pandal architecture and vibrant festive spirit.",
    "kml-073": "Vibrant North Kolkata celebration known for innovative contemporary decor and lively festive community participation.",
    "kml-074": "Popular Bangur Avenue puja known for creative pandal architecture, festive street lighting, and community harmony.",
    "kml-075": "Traditional North Kolkata neighborhood celebration known for heritage rituals, classic sabeki idol, and local warmth.",
    "kml-076": "Historic North Kolkata lane puja noted for heritage architecture, traditional clay idol, and intimate community celebrations.",
    "kml-077": "North Kolkata crowd favorite famous for imaginative, whimsical fantasy themes and unique artistic materials.",
    "kml-078": "Charming Baghbazar neighborhood celebration steeped in traditional Bengali culture, dhak rhythms, and heritage warmth.",
    "kml-079": "Historic Beadon Street barowari celebration known for classic Daker Saaj idol and rich cultural heritage.",
    "kml-080": "Old Kolkata Malapara neighborhood celebration known for traditional craftsmanship, devotional fervor, and community unity.",
    "kml-081": "Heritage North Kolkata merchant quarter puja celebrated for traditional family rituals and historic lane decor.",
    "kml-082": "Traditional Manicktala neighborhood celebration known for warm community hospitality and sabeki idol craftsmanship.",
    "kml-083": "Prominent North Kolkata heritage celebration known for classic sabeki rituals, dhunuchi dance, and festive joy.",
    "kml-084": "Historic North Kolkata neighborhood puja near the Ganges, known for traditional rituals and centuries-old cultural charm.",
    "kml-085": "Vibrant Lake Town park celebration noted for grand architectural facades, lush green surroundings, and festive fairs.",
    "kml-086": "Historic Jawpur sports and physical culture association puja, famous for traditional idol styling and community enthusiasm.",
    "kml-087": "Lake Town residential neighborhood celebration known for artistic pandal decor, colorful lights, and family festivities.",
    "kml-088": "North Kolkata Ultadanga neighborhood puja known for innovative theme concepts, handcrafted decor, and festive warmth.",
    "kml-089": "Prominent Muraripukur community puja celebrated for social art themes, festive lighting, and cultural unity.",
    "kml-090": "Salt Lake Sector-I block puja noted for artistic pandal craftsmanship, quiet residential elegance, and traditional bhog.",
    "kml-091": "Salt Lake Sector-II celebration known for grand decorative pavilions, colorful lighting, and festive community events.",
    "kml-092": "Ultadanga area community club celebrated for creative themes, festive youth energy, and community service.",
    "kml-093": "Historic North Kolkata athletic club puja known for classic idol modeling, festive sports heritage, and local celebrations.",
    "kml-094": "North Kolkata neighborhood puja inspired by Swami Vivekananda's heritage, known for devotional spirit and traditional rituals.",
    "kml-095": "Ultadanga neighborhood celebration noted for colorful artistic pandals, festive music, and community bonding.",
    "kml-096": "Salt Lake Sector-I block celebration known for innovative pandal structures, vibrant cultural programs, and community dining.",
    "kml-097": "Salt Lake Sector-II block puja celebrated for elegant artistic themes, festive lighting, and traditional family atmosphere.",
    "kml-098": "Salt Lake block celebration known for peaceful residential charm, traditional idol modeling, and community cultural nights.",
    "kml-099": "Iconic Central Kolkata cosmopolitan gathering point celebrated for illuminated fairgrounds, festive food, and grand celebrations.",
    "kml-100": "The ultimate cultural heart of South Kolkata Durga Puja, world-famous for its open park gathering, traditional sabeki idol, and lively festive reunions.",
    "kml-101": "Legendary South Kolkata ground celebration known for colossal monumental themes, towering pandal structures, and massive crowd appeal.",
    "kml-102": "Haridevpur's famed art powerhouse celebrated for breathtaking contemporary sculptures, experimental themes, and atmospheric lighting.",
    "kml-103": "Acclaimed Haridevpur theme destination renowned for innovative structural art, surreal concepts, and award-winning craftsmanship.",
    "kml-104": "Prominent Haridevpur sports club puja known for creative thematic installations, vibrant festive music, and cultural events.",
    "kml-105": "Lively Haridevpur park puja noted for artistic pandal architecture, family festive atmosphere, and community harmony.",
    "kml-106": "Traditional Haridevpur neighborhood celebration known for community warmth, cultural programs, and artistic idol styling.",
    "kml-107": "Popular Haridevpur community puja celebrated for creative folk themes, intricate handicrafts, and festive enthusiasm.",
    "kml-108": "South Kolkata powerhouse renowned for deeply moving, award-winning social themes and museum-grade installation art.",
    "kml-109": "Vibrant Barisha neighborhood club celebrated for community welfare initiatives, artistic decor, and traditional rituals.",
    "kml-110": "Charming Behala Sabeda Bagan celebration noted for creative contemporary themes, festive lighting, and community harmony.",
    "kml-111": "Historic South-West Kolkata club renowned for innovative environmental concepts, handcrafted decor, and cultural depth.",
    "kml-112": "Popular Behala destination famous for massive thematic gate structures, inventive materials, and vibrant festive fairs.",
    "kml-113": "Behala landmark celebration known for grand architectural sets, classical Indian temple themes, and festive grandeur.",
    "kml-114": "Historic Behala association puja noted for rich sports heritage, traditional rituals, and community cultural programs.",
    "kml-115": "Warm Behala neighborhood celebration known for colorful artistic pandals, traditional idol, and festive hospitality.",
    "kml-116": "Renowned Kalighat art destination celebrated for pioneering avant-garde themes, exquisite idol modeling, and artistic brilliance.",
    "kml-117": "Major Behala theme destination famous for monumental rural art installations, indigenous crafts, and immersive soundscapes.",
    "kml-118": "Renowned Kasba-Bosepukur art hub celebrated for intricate wooden crafts, folk motifs, and atmospheric illuminations.",
    "kml-119": "Kasba neighborhood crowd-puller known for creative thematic architecture, vibrant lighting, and cultural presentations.",
    "kml-120": "Historic pioneer of Kolkata's theme movement (famous for earthen tea-cup pandal), continuing trailblazing artistic decor.",
    "kml-121": "Prestigious South Kolkata landmark celebrating over 80 years, renowned for magnificent royal temple facades and traditional idol.",
    "kml-122": "Legendary South Kolkata powerhouse famed for authentic Indian temple replicas, massive German chandeliers, and traditional idol.",
    "kml-123": "Premier South Kolkata park celebration known for innovative environmental themes, sprawling fairs, and cultural excellence.",
    "kml-124": "Famous South Kolkata art hub renowned for intricate handicrafts, natural material installations, and poetic aesthetics.",
    "kml-125": "Prestigious Eastern South Kolkata lakeside celebration celebrated for sublime artistic concepts and peaceful festival elegance.",
    "kml-126": "Prestigious South Kolkata landmark celebrated for intricate hand-cut thermocol and wooden filigree art glowing in exquisite symmetry.",
    "kml-127": "Acclaimed Rabindra Sarobar lakeside puja famous for profound philosophical concepts, artistic subtlety, and peaceful charm.",
    "kml-128": "Mega South Kolkata spectacle renowned for colossal avant-garde installations, futuristic themes, and massive crowd pull.",
    "kml-129": "Vibrant Kasba art destination known for impressive architectural installations, colorful lighting, and festive energy.",
    "kml-130": "Acclaimed New Alipore mega-puja featuring rich state-wise cultural themes from across India with custom thematic songs.",
    "kml-131": "Award-winning South Kolkata powerhouse celebrated for blending contemporary installation art with sacred spiritual harmony.",
    "kml-132": "Popular Rashbehari-Pratapaditya Road puja known for creative thematic designs, artistic lighting, and local warmth.",
    "kml-133": "Historic Kalighat-Bhowanipore celebration known for traditional idol craftsmanship, cultural legacy, and festive community bonding.",
    "kml-134": "Watganj-Kidderpore landmark celebration known for grand architectural sets, colorful illuminations, and cultural harmony.",
    "kml-135": "Behala neighborhood club noted for creative contemporary themes, community spirit, and festive gatherings.",
    "kml-136": "Famous Kalighat neighborhood celebration known for progressive social themes, inclusive initiatives, and artistic brilliance.",
    "kml-137": "Acclaimed South Kolkata art hub renowned for exquisite folk art, handloom textiles, and poetic thematic installations.",
    "kml-138": "Charming Lake Market area puja celebrated for traditional idol aesthetics, warm community atmosphere, and cultural nights.",
    "kml-139": "Popular Tollygunge-Azadgarh celebration known for creative thematic pandals, festive lighting, and neighborhood joy.",
    "kml-140": "Regent Park neighborhood puja celebrating traditional Bengali culture, patriotic heritage, and community festivals.",
    "kml-141": "Serene green residential complex puja in Golf Green, known for refined artistic decor, cultural programs, and family bhog.",
    "kml-142": "Santoshpur neighborhood park celebration noted for creative artistic installations, festive fairs, and community harmony.",
    "kml-143": "Vibrant Tollygunge youth club celebrated for energetic festive events, innovative pandal designs, and community bonding.",
    "kml-144": "Prominent Netaji Nagar community puja known for creative social themes, colorful lighting, and neighborhood festivities.",
    "kml-145": "Historic Netaji Nagar socio-cultural club puja noted for traditional rituals, patriotic heritage, and community warmth.",
    "kml-146": "Elegant New Alipore park celebration known for family-friendly ambiance, creative pandal decor, and cultural functions.",
    "kml-147": "Dhakuria-Jodhpur Park neighborhood puja celebrated for artistic craftsmanship, traditional idol, and festive harmony.",
    "kml-148": "Charming Prince Anwar Shah Road park puja noted for warm residential community spirit and traditional rituals.",
    "kml-149": "Historic Bhowanipore celebration celebrated for traditional Daker Saaj idol, classic aristocratic ambiance, and rich heritage.",
    "kml-150": "Famed Dhakuria art powerhouse celebrated for extraordinary coin, currency, and heritage craft replicas of Indian temples.",
    "kml-151": "Popular Barisha neighborhood celebration known for innovative themes, festive illuminations, and community bonding.",
    "kml-152": "Historic Kidderpore-Watganj celebration known for grand decorative pavilions, vibrant lights, and cultural unity.",
    "kml-153": "Kidderpore literary and cultural celebration named in honor of Bengal's great poets, featuring artistic thematic pandals.",
    "kml-154": "South-West Kolkata neighborhood club noted for traditional idol styling, festive enthusiasm, and local gatherings.",
    "kml-155": "Behala 29 Palli celebration known for innovative contemporary theme designs and vibrant neighborhood festivities.",
    "kml-156": "Major Patuli township celebration known for sprawling fairgrounds, creative architectural themes, and festive lights.",
    "kml-157": "Prominent Patuli-Kendua celebration celebrated for artistic craftsmanship, cultural nights, and community dining.",
    "kml-158": "Ballygunge neighborhood celebration near Ekdalia, known for festive lighting, traditional rituals, and warm hospitality.",
    "kml-159": "Prestigious South Kolkata theme destination spearheaded with grand folk art installations and mesmerizing environmental themes.",
    "kml-160": "Historic Chetla community celebration known for traditional idol craftsmanship, cultural functions, and local camaraderie.",
    "kml-161": "Dhakuria-Selimpur neighborhood celebration noted for creative thematic decor, lighting, and community warmth.",
    "kml-162": "Southern Avenue club puja celebrated for traditional idol aesthetics, serene lakeside ambiance, and cultural unity.",
    "kml-163": "Charming Bhowanipore lane celebration known for traditional family warmth, classic rituals, and heritage charm.",
    "kml-164": "Serene residential enclave puja near EM Bypass, known for elegant thematic decor and close-knit community festivities.",
    "kml-165": "Lake Market area celebration noted for social service initiatives, traditional idol, and warm neighborhood festivals.",
    "kml-166": "Kalighat area neighborhood club puja celebrated for youthful energy, creative pandal decor, and festive gatherings.",
    "kml-167": "Southern Avenue youth corner celebration noted for contemporary artistic concepts and serene lakeside surroundings.",
    "kml-168": "Ballygunge 21 Pally celebration renowned for award-winning theme installations, intricate craftsmanship, and cultural depth.",
    "kml-169": "Behala neighborhood puja named after Acharya Prafulla Chandra Ray, celebrating education, science, and traditional culture.",
    "kml-170": "Historic Ballygunge neighborhood celebration known for century-old traditional rituals, sabeki idol, and cultural legacy.",
    "kml-171": "Prestigious South Kolkata institution celebrated for elegant, sophisticated art installations and refined traditional aesthetics.",
    "kml-172": "Barisha sports corner puja celebrated for youth enthusiasm, creative pandal designs, and festive camaraderie.",
    "kml-173": "Popular Barisha club celebration known for community welfare, vibrant lighting, and traditional idol worship.",
    "kml-174": "Barisha neighborhood celebration noted for creative thematic pandal architecture and festive community bonding.",
    "kml-175": "Behala Arcadia residential celebration known for peaceful family festive atmosphere and traditional rituals.",
    "kml-176": "Traditional Behala Durgabari celebration known for devotional purity, Vedic rituals, and classic sabeki idol.",
    "kml-177": "Behala area community club celebrated for creative thematic decor, cultural programs, and festive joy.",
    "kml-178": "Famous South Kolkata institution renowned for deeply emotional social themes, inclusive accessibility, and eco-friendly art.",
    "kml-179": "Haridevpur area neighborhood puja noted for creative contemporary themes, festive lighting, and local harmony.",
    "kml-180": "Santoshpur Sonar Tori celebration famous for boat and riverine artisanal themes, reflecting Bengal's rich water heritage.",
    "kml-181": "Historic Bhowanipore celebration celebrated for traditional rituals, sabeki idol styling, and neighborhood warmth.",
    "kml-182": "Bhowanipore Goal Math park celebration known for spacious grounds, festive fairs, and creative pandal decor.",
    "kml-183": "Barisha Netaji Sangha celebration noted for patriotic heritage, creative thematic installations, and community spirit.",
    "kml-184": "Historic Behala Buroshibtala club celebrated for community welfare, traditional idol, and vibrant festive events.",
    "kml-185": "Behala neighborhood club puja known for creative artistic motifs, colorful lighting, and festive gatherings.",
    "kml-186": "Tollygunge Suryanagar celebration celebrated for innovative theme concepts, handcrafted decor, and community warmth.",
    "kml-187": "Santoshpur area Udayan Sangha puja noted for creative pandal architecture, festive music, and neighborhood bonding.",
    "kml-188": "EM Bypass area Panchanan Gram celebration known for grand decorative pandals, lighting, and community harmony.",
    "kml-189": "Kalighat area Golden Arrow Club puja celebrated for youthful energy, creative themes, and festive enthusiasm.",
    "kml-190": "Kasba Purbachal Shakti Sangha noted for artistic thematic pandals, traditional rituals, and community celebrations.",
    "kml-191": "Behala Naskarpur neighborhood celebration known for traditional idol craftsmanship and warm community hospitality.",
    "kml-192": "Bhowanipore 64 Pally celebration celebrated for creative contemporary themes and intimate neighborhood festivities.",
    "kml-193": "Jodhpur Park 95 Pally celebration renowned for innovative craftsmanship, social art installations, and cultural programs.",
    "kml-194": "Dhakuria Bandhab Sammilani celebration known for close-knit community harmony, traditional idol, and festive meals.",
    "kml-195": "Historic Kalighat training association puja celebrated for youth fitness heritage, traditional rituals, and community spirit.",
    "kml-196": "Historic Kalighat neighborhood celebration known for traditional idol artistry and vibrant festive camaraderie.",
    "kml-197": "Netaji Nagar-Roynagar community puja noted for creative thematic designs, cultural functions, and local joy.",
    "kml-198": "Tollygunge-Shyamapally celebration known for devotional spirit, traditional idol styling, and community warmth.",
    "kml-199": "Garia Sreerampur welfare committee puja celebrated for social initiatives, festive illuminations, and community bonding.",
    "kml-200": "Historic Bhowanipore Swadhin Sangha puja celebrated for freedom-era heritage, traditional rituals, and cultural programs.",
    "kml-201": "Patuli Dakshin Phalguni celebration known for artistic pandal decor, lakeside surroundings, and family festivities.",
    "kml-202": "Historic Garia celebration honoring the divine Pancha Durga heritage with deep devotional reverence and community feasts.",
    "kml-203": "Garia Sabuj Dal community celebration known for eco-friendly green themes, festive illuminations, and cultural events.",
    "kml-204": "Historic Bhowanipore Harish Park celebration celebrated for sprawling park fairs, grand pandal architecture, and rich legacy.",
    "kml-205": "Garia Jatra Suru Sangha puja noted for creative cultural installations, traditional idol, and community enthusiasm.",
    "kml-206": "Haridevpur Judge Bagan recreation club puja celebrated for artistic contemporary themes and festive sports spirit.",
    "kml-207": "Santoshpur Green Avenue celebration known for peaceful residential ambiance, creative decor, and traditional bhog.",
    "kml-208": "Bhowanipore Rupchand Mukherjee Lane puja known for heritage lane lighting, classic sabeki idol, and family warmth.",
    "kml-209": "Santoshpur Agragami celebration celebrated for innovative folk art themes, lighting displays, and community harmony.",
    "kml-210": "Santoshpur Bibekananda Sangha celebration noted for educational and cultural activities, artistic pandal, and festive joy.",
    "kml-211": "Lake Pally Sarbojanin near Southern Avenue, known for serene lakeside surroundings, traditional idol, and cultural events.",
    "kml-212": "Golf Green Phase 1 residential puja celebrated for refined artistic decor, tree-lined festive charm, and community feasts.",
    "kml-213": "Dhakuria 19 Pally celebration celebrated for creative contemporary themes, festive lighting, and neighborhood enthusiasm.",
    "kml-214": "Bhowanipore 68 Pally celebration known for intimate neighborhood charm, traditional rituals, and festive warmth.",
    "kml-215": "Dhakuria 77 Palli celebration noted for creative artistic installations, traditional idol, and community bonding.",
    "kml-216": "Dhakuria Abasarika Club puja celebrated for warm community spirit, festive lighting, and cultural performances.",
    "kml-217": "Famed Bhowanipore art pioneer celebrated since 1928 for commissioning exquisite temple architecture replicas and clay idols.",
    "kml-218": "Haridevpur Adarsha Samiti celebration known for creative contemporary themes, traditional rituals, and community harmony.",
    "kml-219": "Prominent Sarat Bose Road celebration known for grand decorative pavilions, vibrant lights, and festive social gatherings.",
    "kml-220": "Manoharpukur neighborhood celebration celebrated for traditional rituals, sabeki idol modeling, and community warmth.",
    "kml-221": "Manoharpukur Youngs celebration known for youthful festive energy, creative pandal decor, and neighborhood bonding.",
    "kml-222": "Bhowanipore Padmapukur youth club puja celebrated for creative thematic designs, festive music, and community spirit.",
    "kml-223": "Historic Bhowanipore Padmapukur barowari celebration known for classic Daker Saaj idol and rich neighborhood heritage.",
    "kml-224": "Park Circus Uddipani celebration known for vibrant cosmopolitan festive energy, illuminated fairs, and cultural unity.",
    "kml-225": "Southern Avenue Triangular Park celebration known for beautiful park decor, traditional idol, and pleasant festive gatherings.",
    "kml-226": "Barisha Sitalatala Kishore Sangha puja celebrated for youth enthusiasm, traditional rituals, and neighborhood joy.",
    "kml-227": "Behala Prasanta Disha celebration known for social welfare themes, creative decor, and community festivities.",
    "kml-228": "Barisha Yubak Brinda celebration noted for energetic youth participation, colorful lighting, and festive community bonding.",
    "kml-229": "Behala Aikya Sammilani celebration celebrated for communal harmony, traditional idol, and cultural programs.",
    "kml-230": "Historic Central Kolkata celebration established in 1947 near Sealdah station, celebrated for traditional rituals and railway sporting heritage.",
    "kml-231": "Historic Central Kolkata landmark famous for majestic illuminated temple replicas floating on the historic lake water.",
    "kml-232": "Celebrated Central Kolkata ground puja famous for grand replicas of world-famous monuments and brilliant decorative lighting.",
    "kml-233": "Spectacular Central Kolkata mega-puja renowned for ultra-luxurious gold/diamond themed sets, laser shows, and massive crowds.",
    "kml-234": "Renowned North-Central celebration famous for pioneering glass/brass artisanal themes, eco-friendly decor, and spirited dhak contests.",
    "kml-235": "Historic Manicktala temple-precinct puja known for deep devotional rituals, traditional idol styling, and community warmth.",
    "kml-236": "Vibrant Ultadanga neighborhood puja famous for colorful thematic decor, folk artisan motifs, and warm community festivities.",
    "kml-237": "Pioneer of North Kolkata theme pujas along Ultadanga, celebrated for intricate handicrafts, natural material decor, and artistic idols.",
    "kml-238": "Acclaimed North Kolkata art hub celebrated for exquisite terracotta and clay sculpture installations blending heritage with modern aesthetics.",
    "kml-239": "Century-old heritage celebration along the historic Hatibagan theater corridor, noted for traditional idol decor and cultural nostalgia.",
    "kml-240": "Famous Hatibagan theme powerhouse renowned for creative rural and folk art motifs, intricate woodwork, and cultural depth.",
    "kml-241": "Historic North Kolkata puja celebrated for exquisite handcrafted wooden and clay idol artistry and heritage charm.",
    "kml-242": "Award-winning North Kolkata thematic powerhouse celebrated for deeply emotional social, literary, and environmental art installations.",
    "kml-243": "Historic North Kolkata Hedua Park celebration famous for lakeside ambiance, traditional sabeki idol, and cultural legacy.",
    "kml-244": "Historic nationalist puja founded in 1926 with blessings of Netaji Subhas Chandra Bose, famous for its fierce traditional warrior-form idol.",
    "kml-245": "North Kolkata crowd favorite famous for imaginative, whimsical fantasy themes and unique artistic materials.",
    "kml-246": "Energetic North Kolkata youth club puja celebrated for vibrant thematic pandal designs, lighting, and community warmth.",
    "kml-247": "Iconic North Kolkata heritage puja celebrated for magnificent traditional artistry, vibrant cultural themes, and riverside charm.",
    "kml-248": "Energetic Ahiritola youth celebration known for innovative pandal art, colorful illuminations, and festive spirit.",
    "kml-249": "Historic North Kolkata neighborhood puja celebrated for authentic traditional idol artistry, heritage lane decor, and classic rituals.",
    "kml-250": "Grand celebration adjoining the potters' colony, renowned for massive architectural facades and contemporary artistic installations.",
    "kml-251": "Historic North Kolkata neighborhood puja near the Ganges, known for traditional rituals and centuries-old cultural charm.",
    "kml-252": "Historic barowari celebration in Kumartuli, revered for master artisan clay sculpting and sacred traditional heritage.",
    "kml-253": "Historic centenary barowari celebration (est. 1919) famous for its timeless Ekchala Daker Saaj idol, classic rituals, and grand carnival.",
    "kml-254": "Baghbazar 7 Pally celebration noted for traditional community rituals, dhunuchi dance, and festive neighborhood camaraderie.",
    "kml-255": "Sprawling North Kolkata park celebration known for community cultural events, festive fairs, and traditional idol worship.",
    "kml-256": "Pioneering North Kolkata barowari celebration (est. 1921) celebrated for its century-old heritage, traditional idol, and festive fairs.",
    "kml-257": "Renowned for world-class museum-grade installation art and contemporary conceptual architectural installations.",
    "kml-258": "Mega VIP Road attraction renowned for lavish world-famous monument replicas (Burj Khalifa, Vatican, Ram Mandir) and real gold-adorned idols.",
    "kml-259": "Award-winning art destination along Dum Dum Park celebrated for intricate hand-sculpted installations, conceptual themes, and ambient lighting.",
    "kml-260": "Celebrated Dum Dum Park community puja known for creative contemporary pandal themes, festive illuminations, and large footfall.",
    "kml-261": "Premier Dum Dum Park attraction renowned for innovative eco-friendly craftsmanship, contemporary artistic sculptures, and cultural resonance.",
    "kml-262": "Premier Lake Town celebration celebrated for lavish architectural structures, vibrant festive illuminations, and traditional fervor.",
    "kml-263": "Historic 200+ year-old North Kolkata household puja of the illustrious Srimani family, famous for round-the-clock open courtyard hospitality.",
    "kml-264": "Over 200-year-old aristocratic household puja featuring the unique 'Muttchowree' three-spired backdrop and traditional Khaas Bangla face mould.",
    "kml-265": "Historic royal household puja founded in 1757 by Raja Nabakrishna Deb; famed for its grand Natmandir courtyard and Ekchala Daker Saaj idol.",
    "kml-266": "Kolkata's oldest recorded Durga Puja (started in 1610 at Barisha by Lakshmikanta Ray Mazumdar), worshipped in the historic Aatchala mandap.",
    "kml-267": "Aristocratic North Kolkata zamindar mansion puja (est. 1846) with a grand marble Natmandir, dancing hall, and pristine Ekchala idol.",
    "kml-268": "Sacred 18th-century heritage celebration founded by the legendary philanthropist Rani Rashmoni, attended by historic Bengal luminaries.",
    "kml-269": "Historic Beadon Street merchant mansion puja (est. 1770) famed for its exquisite idol flanked by Jaya and Bijaya on swans.",
    "kml-270": "Ancient 450+ year-old household puja where the sacred deity is crafted from touchstone (Kasthipathar) sculpted during Bengal's Pala era.",
    "kml-271": "Renowned Kalighat art destination celebrated for pioneering avant-garde themes, exquisite idol modeling, and artistic brilliance.",
    "kml-272": "Landmark Kalighat neighborhood puja celebrated for progressive themes, artistic decor, and historic community roots.",
    "kml-273": "Historic South Kolkata club showcasing intimate community warmth, traditional rituals, and local festive spirit.",
    "kml-274": "Celebrated South Kolkata theme destination spearheaded with grand folk art installations and mesmerizing environmental themes.",
    "kml-275": "Legendary South Kolkata ground celebration known for colossal monumental themes, towering pandal structures, and massive crowd appeal.",
    "kml-276": "Famous South Kolkata institution renowned for deeply emotional social themes, inclusive accessibility, and eco-friendly art.",
    "kml-277": "Prestigious South Kolkata institution celebrated for elegant, sophisticated art installations and refined traditional aesthetics.",
    "kml-278": "Award-winning South Kolkata powerhouse celebrated for blending contemporary installation art with sacred spiritual harmony.",
    "kml-279": "Acclaimed South Kolkata art hub renowned for exquisite folk art, handloom textiles, and poetic thematic installations.",
    "kml-280": "Prestigious South Kolkata landmark celebrating over 80 years, renowned for magnificent royal temple facades and traditional idol.",
    "kml-281": "Legendary South Kolkata powerhouse famed for authentic Indian temple replicas, massive German chandeliers, and traditional idol.",
    "kml-282": "Ballygunge neighborhood celebration near Ekdalia, known for festive lighting, traditional rituals, and warm hospitality.",
    "kml-283": "Ballygunge 21 Pally celebration renowned for award-winning theme installations, intricate craftsmanship, and cultural depth.",
    "kml-284": "Historic pioneer of Kolkata's theme movement (famous for earthen tea-cup pandal), continuing trailblazing artistic decor.",
    "kml-285": "Renowned Kasba-Bosepukur art hub celebrated for intricate wooden crafts, folk motifs, and atmospheric illuminations.",
    "kml-286": "Vibrant Kasba art destination known for impressive architectural installations, colorful lighting, and festive energy.",
    "kml-287": "Famed Dhakuria art powerhouse celebrated for extraordinary coin, currency, and heritage craft replicas of Indian temples.",
    "kml-288": "Famous South Kolkata art hub renowned for intricate handicrafts, natural material installations, and poetic aesthetics.",
    "kml-289": "Premier South Kolkata park celebration known for innovative environmental themes, sprawling fairs, and cultural excellence.",
    "kml-290": "Jodhpur Park 95 Pally celebration renowned for innovative craftsmanship, social art installations, and cultural programs.",
    "kml-291": "Santoshpur neighborhood park celebration noted for creative artistic installations, festive fairs, and community harmony.",
    "kml-292": "Dhakuria-Jodhpur Park neighborhood puja celebrated for artistic craftsmanship, traditional idol, and festive harmony.",
    "kml-293": "Prestigious Eastern South Kolkata lakeside celebration celebrated for sublime artistic concepts and peaceful festival elegance.",
    "kml-294": "Prestigious South Kolkata landmark celebrated for intricate hand-cut thermocol and wooden filigree art glowing in exquisite symmetry.",
    "kml-295": "Acclaimed New Alipore mega-puja featuring rich state-wise cultural themes from across India with custom thematic songs.",
    "kml-296": "Prominent Sarat Bose Road celebration known for grand decorative pavilions, vibrant lights, and festive social gatherings.",
    "kml-297": "Historic South-West Kolkata club renowned for innovative environmental concepts, handcrafted decor, and cultural depth.",
    "kml-298": "South-West Kolkata celebration rooted in Barisha's historic heritage, featuring traditional rituals and community unity.",
    "kml-299": "Prominent Garia-Raipur community celebration known for creative thematic decor, lighting, and cultural festivities.",
    "kml-300": "Mega South Kolkata spectacle renowned for colossal avant-garde installations, futuristic themes, and massive crowd pull.",
    "kml-301": "The ultimate cultural heart of South Kolkata Durga Puja, world-famous for its open park gathering, traditional sabeki idol, and lively festive reunions.",
    "kml-302": "Behala 11 Pally celebration noted for creative thematic installations, festive lighting, and neighborhood camaraderie.",
    "kml-303": "Salt Lake's most celebrated mega-puja, attracting lakhs of visitors for its colossal fantasy architecture, laser shows, and grand themes.",
    "kml-304": "Salt Lake Sector-II block puja celebrated for royal architectural temple replicas, colorful illuminations, and community fairs.",
    "kml-305": "Prominent Salt Lake Sector-I puja celebrated for monumental architecture, cultural programs, and grand community dining.",
    "kml-306": "Salt Lake Sector-II block puja noted for traditional idol craftsmanship, festive illuminations, and community cultural performances.",
    "kml-307": "Salt Lake Sector-I block celebration known for innovative thematic decor, artistic lighting, and warm community feasts.",
    "kml-308": "Popular Salt Lake Sector-I celebration known for creative handicrafts, traditional idol modeling, and cultural events.",
    "kml-309": "Salt Lake Sector-I block celebration celebrated for artistic pandal designs, festive lights, and family harmony.",
    "kml-310": "Salt Lake Sector-I block puja noted for artistic pandal craftsmanship, quiet residential elegance, and traditional bhog.",
    "kml-311": "Salt Lake Sector-II celebration known for grand decorative pavilions, colorful lighting, and festive community events.",
    "kml-312": "Salt Lake block celebration known for peaceful residential charm, traditional idol modeling, and community cultural nights.",
    "kml-313": "Salt Lake Sector-II block puja noted for elegant thematic decor, traditional rituals, and warm residential gatherings.",
    "kml-314": "Salt Lake Sector-I residential celebration known for creative artistic motifs, traditional idol, and community dining.",
    "kml-315": "Salt Lake Sector-I block puja celebrated for architectural replicas, colorful illuminations, and festive cultural nights.",
    "kml-316": "Salt Lake Sector-I block celebration known for peaceful festive atmosphere, traditional rituals, and family gatherings.",
    "kml-317": "Salt Lake Sector-I block puja celebrated for creative theme installations, artistic decor, and community camaraderie.",
    "kml-318": "Vibrant Salt Lake Sector-I block puja known for creative artistic craftsmanship, lighting displays, and family celebrations.",
    "kml-319": "Salt Lake Sector-II block puja celebrated for elegant artistic themes, festive lighting, and traditional family atmosphere.",
    "kml-320": "Salt Lake Sector-II block celebration known for traditional idol worship, festive lighting, and close-knit community spirit.",
    "kml-321": "Famous Salt Lake ground puja celebrated for magnificent palace replicas, festive fairs, and massive community gatherings.",
    "kml-322": "Salt Lake Sector-II block celebration noted for creative architectural decor, cultural programs, and festive harmony.",
    "kml-323": "Salt Lake Sector-II block puja celebrated for traditional idol aesthetics, serene residential charm, and community feasts.",
    "kml-324": "Salt Lake Sector-I block celebration known for innovative pandal structures, vibrant cultural programs, and community dining.",
    "kml-325": "Salt Lake Sector-I block puja celebrated for creative theme craftsmanship, festive illuminations, and cultural events.",
    "kml-326": "Salt Lake Sector-I block celebration known for artistic pandal designs, traditional rituals, and family festivities.",
    "kml-327": "Salt Lake Sector-I block puja noted for peaceful residential elegance, traditional idol modeling, and community bhog.",
    "kml-328": "Historic Salt Lake estate celebration known for serene residential ambiance, traditional rituals, and warm community bhog.",
    "kml-329": "Salt Lake Sector-III block celebration known for creative thematic decor, festive illuminations, and community unity.",
    "kml-330": "Salt Lake Sector-III block puja celebrated for elegant architectural designs, cultural performances, and festive warmth.",
    "kml-331": "Charming Salt Lake block puja celebrated for traditional idol modeling, cultural unity, and festive community feasts.",
    "kml-332": "Salt Lake Sector-III block celebration noted for artistic craftsmanship, colorful lighting, and family gatherings.",
    "kml-333": "Vibrant Salt Lake residential celebration featuring artistic pandal architecture, festive lighting, and cultural programs.",
    "kml-334": "Popular Salt Lake block puja known for creative artistic motifs, eco-friendly materials, and traditional family warmth.",
    "kml-335": "Salt Lake Sector-III block puja celebrated for traditional idol aesthetics, serene residential charm, and community feasts.",
    "kml-336": "Salt Lake Sector-III block celebration known for grand decorative pavilions, festive lighting, and cultural harmony.",
    "kml-337": "Salt Lake Sector-III block celebration noted for creative thematic installations, traditional rituals, and festive joy.",
    "kml-338": "Salt Lake Sector-III block puja celebrated for innovative decor, lively cultural nights, and community dining.",
    "kml-339": "Vibrant Salt Lake commercial and residential hub puja known for festive illuminations, food fairs, and community gatherings.",
    "kml-340": "Salt Lake residential block puja noted for peaceful festive ambiance, traditional rituals, and cultural gatherings.",
    "kml-341": "Salt Lake Sector-I block puja celebrated for architectural replicas, festive lighting, and close-knit community spirit.",
    "kml-342": "Salt Lake Sector-I block celebration known for traditional idol worship, festive lighting, and neighborhood harmony.",
    "kml-343": "Renowned Salt Lake Sector-II celebration known for grand royal temple architecture, cultural performances, and traditional idol.",
    "kml-344": "Salt Lake Sector-II block celebration celebrated for creative thematic designs, festive music, and community spirit."
}

updated_count = 0
for p in pandals:
    pid = p["id"]
    name = p["name"]
    category = p.get("category", "")
    
    if pid in CUSTOM_DESCRIPTIONS:
        p["description"] = CUSTOM_DESCRIPTIONS[pid]
        updated_count += 1
    else:
        # Fallback if any missing: construct high quality concise description
        clean_name = re.sub(r'\s*(Durga Puja|Sarbojonin|Sarbojanin|Durgotsav|Durgatsab|Committee|Pandal|Club|Association).*', '', name, flags=re.I).strip()
        if "Salt Lake" in category:
            p["description"] = f"Salt Lake {clean_name} celebration celebrated for magnificent pandal architecture, festive illuminations, and vibrant community culture."
        elif "Bonedi" in category:
            p["description"] = f"Historic aristocratic Bengali household puja of {clean_name}, celebrated for centuries-old heritage, Vedic rituals, and traditional Ekchala idol."
        elif "South" in category:
            p["description"] = f"Popular South Kolkata celebration at {clean_name}, renowned for creative thematic artistry, festive lighting, and cultural spirit."
        else:
            p["description"] = f"Famous Kolkata celebration at {clean_name}, known for traditional idol craftsmanship, festive illuminations, and community heritage."
        updated_count += 1

with open("client/src/data/kml-pandals.json", "w", encoding="utf-8") as f:
    json.dump(pandals, f, indent=2, ensure_ascii=False)

print(f"Successfully updated descriptions for all {updated_count} pandals!")
